### ISSUE TITLE
Spatial/Series refactor tracker

### ISSUE THREAD

**Issue by Lun4m** [metno/rove#69]
Per @intarga comment on #66.

- [x] #70
- [x] Change DataConnector trait
- [x] Merge validate_spatial and validate_series
- [x] ~~Filter out flagged data from tests~~
- [x] Tackle validate_fresh &rarr; moved to #77

**Comment by intarga** [comment]
Updates to this issue as things have changed.

Points 2 and 3 are resolved by #76 

Point 4 is no longer valid, since we decided that filtering should happen inside the relevant tests themselves. This becomes an Olympian issue.

Point 5 I'm splitting out into a down-prioritised new issue (#77), since I realised validate_fresh is just a special case of validate (earlier referred to as validate_periodic). It's probably still worth doing, but I'm considering it as an optimisation rather than a structural blocker.

As a consequence I'm marking this whole issue as resolved by #76
